### ISSUE TITLE
RFC-3: Should the amount be optional?

### ISSUE THREAD

**Issue by emschwartz** [interledger/rfcs#103] opened 2016-09-27 16:35 UTC
Based on discussion in https://github.com/interledger/rfcs/issues/100

**Comment by adrianhopebailie** [comment] 2016-09-28 09:31
Is there a good reason to make it optional? i.e. Are the scenarios when it will be difficult to provide?

If so, do we need to define different normative behavior when the amount is present vs not?

As I said in #100:

> As a connector, it's conceivable that (especially for a high value payment) I get a quote request that contains an amount to deliver and address to deliver to.

> I may, as a way to ensure I give my peers consistent service, wish to keep a record of the quotes I give and ensure I deliver on that quote, for at least a short period of time.

For that reason it is useful to rely on getting the amount in every packet, suggesting it should not be optional.

**Comment by justmoon** [comment] 2016-09-28 12:02
One use case I can think of is wanting to do a payment without having to quote first. Suppose I know the source amount and I don't care how much money gets there. So I just send off an ILP packet with a payment using the source amount.

Now the reason I was originally against making the amount optional was that it puts connectors in an odd position. If I'm a connector, how much of a fee should I take? 1% 5% 10%? There isn't a clear limit. Maybe if I take a larger fee the payment is less likely to complete, but who knows?

We could assume that connectors just charge the same that they would for a normal payment. But as a connector what's my reason for doing so? 

1. If there is no incentive to charge the same, then maybe I'll charge double or triple my normal fee. The payment will likely still complete. There isn't really a clear stopping point, the connector is playing a game of chicken.

  From the user's perspective then - isn't it easier to quote first and remove the temptation by connectors to overcharge?

2. One possible incentive could be that my customers prefer it. I.e. if I'm a connector and my customers know that I charge the same for payments with no destination amount that I would have charged otherwise, they'll be happier with me. If that incentive turns out to be sufficient, then optional amounts are a useful feature.

Right now I'm leaning more towards adopting the second viewpoint which would mean yes to optional amounts. The reason is that we are already making similar assumptions about connector relationships in general. I.e. we predict that most users will just peer with one connector. So what's stopping that connector from quoting too much? They know that over time if they keep doing that, the user will switch to somebody else.

The same argument could apply here: If I charge more for payments with no destination amount then my users will eventually notice and not want to use my service anymore.

**Comment by adrianhopebailie** [comment] 2016-10-10 09:31
I think we can close this.

Amount can be optional but we need to define the expected behaviour of connectors in both scenarios.

**Closed** 2016-10-10 14:10 UTC
