### ISSUE TITLE
RFC-4: Change RejectionMessage to match ILP (RFC-3)

### ISSUE THREAD

**Issue by justmoon** [interledger/rfcs#332] opened 2017-11-07 14:54 UTC
There are a couple of issues with the RFC-4 [RejectionMessage](https://github.com/interledger/rfcs/blob/75d819d5947c6cee94510b7b1cd009e1627fc748/0004-ledger-plugin-interface/0004-ledger-plugin-interface.md#class-rejectionmessage):

* `forwarded_by` should be an array
* `message` does not exist in the ILP packet and should presumably move to `additional_info`

**Comment by michielbdejong** [comment] 2017-11-14 12:55
This would break all existing plugins, right? What problems are caused by it currently not being an array?

**Comment by justmoon** [comment] 2017-11-14 20:55
No, the plugins are *currently* broken, this would fix them. Forwarded by is an array in ILP, this is just a bug in the LPI that propagated to the plugins.

**Comment by michielbdejong** [comment] 2017-11-14 21:06
Interesting! Reminds me of https://en.wikipedia.org/wiki/HTTP_referer#Etymology.

**Comment by emschwartz** [comment] 2017-12-05 19:20
Given https://github.com/interledger/rfcs/pull/347, I think we can leave LPIv1 as it is and make sure to include these changes in v2

**Comment by emschwartz** [comment] 2017-12-05 20:28
@justmoon can we close this?

**Closed** 2017-12-21 20:49 UTC
